import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Backtrack | Version Your Music",
  description:
    "Backtrack is your dedicated tool for effortless version control and collaboration in music production. Simplify your workflow, merge creative ideas, and say goodbye to endless email exchanges. Explore our future plans for an enhanced user experience and stay tuned for more exciting features!",
  icons: {
    icon: "/icon.png",
  },
  keywords: [
    "Music versioning",
    "Music history",
    "History",
    "Versioning",
    "Music collaboration",
    "Version control for music",
    "Music creation tool",
    "Digital audio workstation (DAW)",
    "Music project management",
    "Songwriting software",
    "Music composition",
    "Music collaboration platform",
    "Song version tracking",
    "Music file management",
    "Music workflow optimization",
    "Audio project collaboration",
    "Music project synchronization",
    "Music collaboration tool",
    "Music production",
    "Song recording",
    "Audio editing",
    "Music software",
    "Sound production",
    "Music technology",
    "Sound engineering",
    "Music arrangement",
    "Creative music",
    "Music innovation",
    "Song arrangement",
    "Audio collaboration",
    "Digital music creation",
    "Music project versioning",
    "Music project collaboration",
    "Audio version tracking",
    "Music revision control",
    "Audio project versioning",
    "Song collaboration tool",
    "Collaborative music creation",
    "Music project organization",
    "Songwriter collaboration",
    "Songwriting collaboration",
    "Music file versioning",
    "Track versioning",
    "Sound project management",
    "Collaborative songwriting",
    "Music collaboration workflow",
    "Creative audio collaboration",
    "Music project coordination",
    "Audio project organization",
    "Song version management",
    "Music collaboration innovation",
    "Songwriting version control",
    "Collaborative music production",
    "Music collaboration efficiency",
    "Audio file versioning",
    "Songwriting project management",
    "Music collaboration platform",
    "Song creation collaboration",
    "Digital audio collaboration",
    "Collaborative music technology",
    "Music project file management",
    "Song collaboration and editing",
    "Music project version control",
    "Audio production collaboration",
    "Music file version control",
    "Music collaboration creativity",
    "Songwriting project collaboration",
    "Music collaboration system",
    "Songwriting versioning tool",
    "Collaborative audio editing",
    "Music collaboration interface",
    "Audio collaboration platform",
    "Digital song creation",
    "Collaborative sound production",
    "Music collaboration application",
    "Song version collaboration",
    "Collaborative music arrangement",
    "Music project innovation",
    "Audio collaboration tool",
    "Songwriting workflow optimization",
    "Music collaboration organization",
    "Song version control",
    "Music collaboration technology",
    "Collaborative music software",
    "Music project coordination tool",
    "Songwriter collaboration platform",
    "Songwriting collaboration tool",
    "Music file version tracking",
    "Music collaboration toolset",
    "Collaborative song creation",
    "Music collaboration platform",
    "Songwriting collaboration system",
    "Digital music collaboration",
    "Music project versioning tool",
    "Audio project version control",
    "Song collaboration and versioning",
    "Music collaboration software",
    "Song version management tool",
    "Music collaboration framework",
    "Collaborative music versioning",
    "Music collaboration management",
    "Audio collaboration innovation",
    "Music project version tracking",
    "Songwriting version management",
    "Music collaboration interface tool",
    "Collaborative audio project management",
    "Music collaboration workflow tool",
    "Song versioning and collaboration",
    "Music collaboration tool innovation",
    "Collaborative music creation platform",
    "Music project version control tool",
    "Song collaboration and production",
    "Music collaboration coordination",
    "Songwriting version control system",
    "Collaborative audio project versioning",
  ],
  authors: {
    name: "Tika Capon",
    url: "https://github.com/tika",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
